DjangoPlotLy/site1/app1/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # /app1
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^plot1d/$', views.Plot1DView.as_view(), name='plot1d'),
    url(r'^plot2d/$', views.Plot2DView.as_view(), name='plot2d'),
    url(r'^plot3d/$', views.Plot3DView.as_view(), name='plot3d'),
    url(r'^plot1d_multiple/(?P<n>\d+)/$',
        views.Plot1DMultipleView.as_view(), name='plot1d_multiple'),
    url(r'^plot1d_multiple_ajax/(?P<n>\d+)/$',
        views.plot1d_multiple_ajax, name='plot1d_multiple_ajax'),
    url(r'^plotIq/$', views.PlotIqView.as_view(), name='plotIq'),
    url(r'^plot_live/$', views.PlotLiveView.as_view(), name='plot_live'),
    url(r'^plot_live_update/$', views.plot_live_update, name='plot_live_update'),
    url(r'^prague/time/$', views.Plot3DScatterViewPragueTime.as_view(), name='plot3d_scatter_time_prague'),
    url(r'^spb/time/$', views.Plot3DScatterViewSpbTime.as_view(), name='plot3d_scatter_time_spb'),
    url(r'^prague/day_of_year/$', views.Plot3DScatterViewPragueDayOfYear.as_view(), name='plot3d_scatter_year_day_prague'),
    url(r'^spb/day_of_year/$', views.Plot3DScatterViewSpbDayOfYear.as_view(), name='plot3d_scatter_year_day_spb'),
    url(r'^prague/day_of_week/$', views.Plot3DScatterViewPragueDayOfWeek.as_view(), name='plot3d_scatter_week_day_prague'),
    url(r'^spb/day_of_week/$', views.Plot3DScatterViewSpbDayOfWeek.as_view(), name='plot3d_scatter_week_day_spb'),


]

DjangoPlotLy/site1/site1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/app1/'), name='index'),
    url(r'^app1/',  include(('app1.urls', 'app1'), namespace='app1', )),
]

DjangoPlotLy/site1/app1/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

DjangoPlotLy/site1/app1/views.py
import logging

from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.views.generic import TemplateView

from . import plots

logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = "index.html"


class Plot1DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot1DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot1d()
        return context


class Plot2DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot2DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot2d()
        return context


class Plot3DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3d()
        return context


class Plot1DMultipleView(TemplateView):
    template_name = "plot_multiple.html"

    def get_context_data(self, **kwargs):
        n = int(kwargs['n'])
        # Call the base implementation first to get a context
        context = super(Plot1DMultipleView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot1d_multiple(n)
        return context


def plot1d_multiple_ajax(request, n):
    """
    Only handles AJAX queries
    """
    logger.debug("Plotting {} plots.".format(n))
    return HttpResponse(plots.plot1d_multiple(int(n)))


class PlotIqView(TemplateView):
    template_name = "plot_fit.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PlotIqView, self).get_context_data(**kwargs)
        context['plot'] = plots.plotIq()
        return context


class PlotLiveView(TemplateView):
    template_name = "plot_live.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PlotLiveView, self).get_context_data(**kwargs)
        context['plot'] = plots.plotLive()
        return context


def plot_live_update(request):
    '''
    Handle ajax call to update the live plot
    '''
    if request.is_ajax():
        logger.debug("Live plot updated...")
        data = plots.live_plot_get_data_serialized()
        # In order to allow non-dict objects to be serialized set the safe
        # parameter to False
        return JsonResponse([data], safe=False)
    else:
        return HttpResponseBadRequest()


class Plot3DScatterViewPragueTime(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewPragueTime, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_prague_time
        return context


class Plot3DScatterViewSpbTime(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewSpbTime, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_spb_time
        return context


class Plot3DScatterViewSpbTime(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewSpbTime, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_spb_time
        return context


class Plot3DScatterViewSpbDayOfYear(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewSpbDayOfYear, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_spb_day_of_year()
        return context


class Plot3DScatterViewPragueDayOfYear(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewPragueDayOfYear, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_prague_day_of_year()
        return context


class Plot3DScatterViewSpbDayOfWeek(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewSpbDayOfWeek, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_spb_day_of_week()
        return context


class Plot3DScatterViewPragueDayOfWeek(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterViewPragueDayOfWeek, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter_prague_day_of_week()
        return context

DjangoPlotLy/site1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <title>PlotLy OffLine examples</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  {% endblock %}
</head>
<body>
  {% block content %}
  <!-- Content goes here -->

  {% endblock %}

  {% block tail %}
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  {% endblock %}
</body>
</html>

DjangoPlotLy/site1/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h1>Integrating PlotLy into DJango</h1>
  <p class="lead">Click on the buttons below to see the examples.</p>
</div>

<div class="container">
  <table class="table table-striped table-hover">
    <tr>
      <td>1D</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot1d' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>2D</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot2d' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>Random 1D (Ajax)</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot1d_multiple' 1 %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>SANS Iq</td>
      <td><a class="btn btn-default" href="{% url 'app1:plotIq' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>Live Plot 2D</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot_live' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter. Prague (z=time) </td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d_scatter_time_prague' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter. Spb (z=time) </td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d_scatter_time_spb' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter. Prague (z=day of year) </td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d_scatter_year_day_prague' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter. Spb (z=day of year) </td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d_scatter_year_day_spb' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter. Prague (z=day of week) </td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d_scatter_week_day_prague' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter. Spb (z=day of week) </td>
      <td><a class="btn btn-default" href="{% url 'app1:plot3d_scatter_week_day_spb' %}" role="button">View</a></td>
    </tr>
  </table>
</div>
<!-- /.container -->

{% endblock %}

DjangoPlotLy/site1/templates/plot.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Plot using Plot.ly</h1>
  <p class="lead">Here we go...</p>
</div>
<!-- /.container -->

<div class="container">
  <div class="row" style="border: 1px solid black">
    {# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
    <div class="col-md-12">{{plot|safe}}</div>
  </div>
</div>
<!-- /.container -->


<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>

{% endblock %}

DjangoPlotLy/site1/templates/plot_fit.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Plot using Plot.ly and some clever JavaScript</h1>
  <p class="lead">Select some points (Box or Lasso tool) from the plot and see them printed.</p>
</div>

<div class="container">
  <div class="row" style="border: 1px solid black">
    <div id="plot_container" class="col-md-12">{{plot|safe}}</div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <br/>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <pre>
        var myDiv = $('.plotly-graph-div')[0];
        myDiv.on('plotly_selected', function(eventData) {
          console.log(eventData.points);
          for (var idx = 0; idx < eventData.points.length; idx++) {
            console.log(eventData.points[idx]);
          };
        });
      </pre>
    </div>
  </div>
</div>

<div class="container">
  <p>Selected points:</p>
  <pre id="selected_points">

  </pre>
</div>

<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
<!-- /.container -->
{% endblock %}

{% block tail %}
{{block.super}}
<script>
    var myDiv = $('.plotly-graph-div')[0];
    myDiv.on('plotly_selected', function(eventData) {
      console.log(eventData.points);
      $("#selected_points").empty();
      for (var idx = 0; idx < eventData.points.length; idx++) {
        // console.log(eventData.points[idx]);
        $("#selected_points").append(
          "<strong>" + eventData.points[idx].data.name + "</strong>=(" + eventData.points[idx].x + "," + eventData.points[idx].y + ") "
        );
      };
    });
</script>
{% endblock %}

DjangoPlotLy/site1/templates/plot_live.html
{% extends "base.html" %}
{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
    <h1>Live Plot using Plot.ly</h1>
    <p class="lead">Update every few seconds</p>
</div>
<!-- /.container -->

<div class="container">
  <div class="row">
    <div class="col-md-12">{{plot|safe}}</div>
  </div>
</div>
<!-- /.container -->

<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
<!-- /.container -->

<script type="text/javascript">
    (function poll() {
        setTimeout(function() {
            $.ajax({
                type: "GET",
                url: "{% url 'app1:plot_live_update' %}",
                success: function(data) {
                    var plot_div = $('.plotly-graph-div')[0];
                    // If the new data is an update to the old one
                    // var old_data = plot_div.data;
                    // old_data[0].x = old_data[0].x.concat(data[0].x);
                    // old_data[0].y = old_data[0].y.concat(data[0].y);
                    // Plotly.newPlot(plot_div,old_data, plot_div.layout);
                    Plotly.newPlot(plot_div,data, plot_div.layout);
                },
                dataType: "json",
                complete: poll,
                timeout: 2000
            })
        }, 1000);
    })();
</script>


{% endblock %}

DjangoPlotLy/site1/templates/plot_multiple.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Plot using Plot.ly</h1>
  <p class="lead">Ajax test!</p>
</div>
<!-- /.container -->

<div class="container">
  <div class="row">
    <div class="col-md-12"><div id="plot">{{plot|safe}}</div></div>
  </div>
</div>
<!-- /.container -->

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <button id="button" type="button" class="btn btn-primary" data-loading-text="Loading..." >Change number of graphics</button>
      <div id=time></div>
    </div>
  </div>
</div>
<!-- /.container -->

<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
{% endblock %}

{% block tail %}
{{block.super}}
<script>
// Set up the buttons
$("#button").click(function() {
  var btn = $(this);
  btn.button('loading');
  // Then whatever you actually want to do i.e. submit form
  // After that has finished, reset the button state using
  var n = Math.floor((Math.random() * 50) + 1);
  $.ajax({
    url: "{% url 'app1:plot1d_multiple_ajax' n=1234 %}".replace('1234',""+n),
    type: 'get', // This is the default though, you don't actually need to always mention it
    success: function(data) {
        $('#plot').empty().append(data);
        btn.button('reset');
    },
    failure: function(data) {
        alert('Got an error dude!');
        btn.button('reset');
    },
    start_time: new Date().getTime(),
    complete: function(data) {
        var message = 'Time: '+(new Date().getTime() - this.start_time)+' ms for ' + n + ' lines.';
        // console.log(message);
        $("#time").html('<br/><p class="lead">' + message + '</p>');
    }
  });

});
</script>
{% endblock %}